### ISSUE TITLE
cache blocking / packing implementation for GEMM

### ISSUE THREAD

**Issue by yzhaiustc** [pangxie100/HPC-pairwise-distance-optimization#2]
Thanks for your nice work on profiling.
To init the next phase of your master's project, you may want to try optimizing GEMM on either CPU or GPU.
Following our previous discussion, you prefer exploring the CPU GEMM optimization. Therefore, we can start from here.
1. Please try to implement the cache blocking version of GEMM, with arbitary blocking parameters Mc, Nc and Kc. You may choose not to take care of the edge case at this moment.
2. Please consider to pack the submatrices into continuous memory space before entering the GEMM macro kernel to reduce TLB miss.
The implementation layout is like:
```
for n_count = 0; n_count < N; n_count +=  n_inc{
    n_inc = N-n_count > Nc? Nc : N-n_count;
    for k_count = 0; k_count < K; k_count +=  k_inc{
        k_inc = K-k_count > Kc? Kc : K-k_count;
        packing the k_inc X n_inc of submatrix B into B_buffer
        for m_count = 0; m_count < M; m_count += m_inc{
            m_inc = M-m_count > Mc? Mc : M-m_count;
            packing the m_inc X k_inc of submatrix A into A_buffer
            macro_kernel of GEMM: compute C (m_inc X n_inc) += A_buffer * B_buffer.
        }
    }
}
```
The macro kernel can be implemented by any code you like, such as SIMD intrinsics. You don't have to touch inline ASM at this moment.

**Comment by yzhaiustc** [comment]
http://jianyuhuang.com/papers/sc16.pdf

**Comment by pangxie100** [comment]
The implementation of the cache blocking version of GEMM and packing version of GEMM have been completed. Now I'am trying to use avx512 and kernel 24 * 8 to implement a new version.

To ignore the edge case,  I changed test matrix size from "m = 100 - 3000,  n = 100 - 3000, k = 100 - 3000" to "m = 192 - 192 * 20,  n = 96 - 96 * 20, k = 384 - 384 * 20". The performance kernel 9 (cache blocking + packing) looks like this:   
![image](https://user-images.githubusercontent.com/38969048/130337514-38505a9c-6240-4aa2-aa89-e30e8f5ddf22.png)
![image](https://user-images.githubusercontent.com/38969048/130337529-320ac5c3-b3c7-4384-9788-d801d9b41a90.png)

**Comment by yzhaiustc** [comment]
Cool and thnx.
Next step, you may want to 1) compute the peak performance on our turing4 machine regarding AVX2 and AVX512 fp64 serial DGEMM. 2) if AVX2 is faster, consider what the reason is. 3) try your best to provide a near-optimal solution of AVX2 DGEMM.
Here are some references might be helpful:
https://en.wikichip.org/wiki/intel/xeon_silver/4216
https://github.com/xianyi/OpenBLAS/blob/develop/kernel/x86_64/sgemm_kernel_8x4_haswell_2.c
LMK if you have any questions.

**Comment by yzhaiustc** [comment]
Let me close this issue and init a new one.
